### ISSUE TITLE
ts-mocha ignores code errors in tests

### ISSUE THREAD

**Issue by aimichal** [piotrwitek/ts-mocha#49]
I have a test file which has a typo in the `import` statement, but the test still passes. Is there a way to make the test fail due to compilation errors?

Example:

```
$ mkdir ts-mocha-syntax-errors
$ cd ts-mocha-syntax-errors
$ npm init -y
$ npm install typescript expect mocha ts-mocha
$ vi tsconfig.json
$ cat tsconfig.json
{
    "compilerOptions": {
        "esModuleInterop": true
    }
}
$ vi test.ts
$ cat test.ts
import expect from 'expect';
import {Blah, Blah, Blah} from '../something';

describe('numbers', () => {
    it('fourty two is fourty two', async () => {
        expect(42).toEqual(42);
    });
});
$ node_modules/ts-mocha/bin/ts-mocha test.ts


  numbers
    ✓ fourty two is fourty two


  1 passing (8ms)
```

That `import {Blah, Blah, Blah} from '../something';` is an error. `tsc test.ts` correctly reports errors like `test.ts:2:32 - error TS2307: Cannot find module '../something'.`.

**Comment by piotrwitek** [comment]
Right now it's locked in transpile only mode so no type checking when running tests as it's much faster, but It's possible to extend the configuration.
PR's welcome.

**Comment by bvanreeven** [comment]
Hi @piotrwitek, first off thanks for creating `ts-mocha`! We plan on using this for several projects in our codebase. Due to this issue, we currently have a separate compilation step to check the test code for compile errors, which makes our setup more complex and less performant. Therefore I created a [pull request](https://github.com/piotrwitek/ts-mocha/pull/67) that addresses this issue. Please let me know if there's anything I can do to help get this merged. Thanks!
